### ISSUE TITLE
Aim

### ISSUE THREAD

**Issue by nymann** [bierproductie/management#19]
Aim: Short description of what you planto achieve.

**Comment by Kechr** [comment]
Can be found here: https://docs.google.com/document/d/15z5q1OxnKfeT-uzwdELoB1ElEfOLHqijzGW-rlnmGR8/edit

**Comment by Kechr** [comment]
Reviewed by:
- [ ] Jakob
- [x] Kenneth
- [x] Kevin
- [ ] Kristian
