### ISSUE TITLE
General Corrections

### ISSUE THREAD

**Issue by Kechr** [bierproductie/management#199]
- [x] Write the report in the present tense
- [x] Capitalise the E, F or T when referring to the equation, tables and figures
- [x] Tables in the appendix should not be in the list of tables
- [x] Table text should be above the table (\captionof{table}{Test title} above \begin{tabularx})
- [x] Make sure figures are all good
- [x] Remember to add intro to sections
  - [x] Theory & Methods
  - [x] Requirements
  - [x] Design
  - [x] Implementation
- [x] More detailed and more explanations
- [x] Error function  
  - The only way to estimate the error is to use the batch data.
  - Plot the number of rejected products and make a graph - this is our estimated error function
- [x] Is the TOC placed correctly? Should it be placed after Editorial maybe?
- [x] Change the hand in date on the front page and signature page
- [x] Remove draft from the signature page
- [x] Change page and appendix number on the signature page
- [x] Capatalise Execution and System on front page
- [x] Remove ^1213 from R09 description in List of Requirements Table
- [x] Oxford comma or not? that is the question.
- [x] Capital letters or not? (API, Client, Dashboard etc.)
- [x] Frontend or dashboard?

**Comment by kkmp-dk** [comment]
Ahh jeg troede general corrections blev commit til den branch som er blevet oprettet?

**Comment by kkmp-dk** [comment]
![image](https://user-images.githubusercontent.com/55736468/102009055-2d72ee80-3d35-11eb-8fda-354022db58f3.png)

Is this picture wrong? does it need the database on it ?

**Comment by nymann** [comment]
> ![image](https://user-images.githubusercontent.com/55736468/102009055-2d72ee80-3d35-11eb-8fda-354022db58f3.png)
> 
> Is this picture wrong? does it need the database on it ?

Yep

**Comment by kkmp-dk** [comment]
![System overview v0 0 1](https://user-images.githubusercontent.com/55736468/102010220-091b1000-3d3d-11eb-9dfa-41dca0fa898a.png)

**Comment by kkmp-dk** [comment]
![System overview v0 0 1_white_background](https://user-images.githubusercontent.com/55736468/102010253-3ebff900-3d3d-11eb-9afa-5b8628144b0f.png)
