### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by nymann** [bierproductie/management#24]
What will your approach be?
e.g., Scrum. What technologies are you going to use?

# Information to the writer
- We are using SCRUM (note that this is not really SCRUM, since we have to fit this in to a waterfall project)
- 2 week sprints
- ZenHub

**Comment by Kechr** [comment]
Review can be made here: https://www.dropbox.com/s/5n7ilwop2hw8ikw/draft.docx?dl=0

**Comment by Kechr** [comment]
Reviewed by:
- [ ] Jakob
- [ ] Kevin
- [ ] Kristian
- [ ] Simon

**Comment by nymann** [comment]
Please review this in the linked pull requests instead.
