### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by nymann** [bierproductie/management#26]
Project Organization: How is work distributed across the team and how do you organize your project work?Isthere a project leader?Does anyone assumea special Scrumrole?

### Notes
Kehcr19: SCRUM master
Kjako19: Product Owner

- Work is distributed from planning meetings according to estimations.

**Comment by Kechr** [comment]
Review can be made here: https://www.dropbox.com/s/5n7ilwop2hw8ikw/draft.docx?dl=0

**Comment by Kechr** [comment]
Reviewed by:
- [ ] Jakob
- [ ] Kevin
- [ ] Kristian
- [ ] Simon

**Comment by nymann** [comment]
Please review this in the linked pull requests instead.
