### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by Joergenson** [bierproductie/management#30]
### Notes
Snak om sprints

**Comment by Kechr** [comment]
Review can be made here: https://www.dropbox.com/s/5n7ilwop2hw8ikw/draft.docx?dl=0

**Comment by Kechr** [comment]
Reviewed by:
- [ ] Jakob
- [x] Kevin
- [ ] Kristian
- [ ] Simon

**Comment by nymann** [comment]
Please review this in the linked pull requests instead.
