### ISSUE TITLE
Group 05 review: overall comments

### ISSUE THREAD

**Issue by Kechr** [bierproductie/management#66]
- The overall content seems great and fitting in a lot of sections, however, it can sometimes be superficial.
- The project is a problem-oriented project, so a problem statement would be great to have.
-  SCRUM is used as an agile-process method, which is good –where both a Product Owner and a Scrum Master has been chosen.
- Good that both a Project Plan and Milestone plan has been developed.
- In the section“Risk” there could a better categorization of business-related risks and technical-related risks.
- Even though a tentative structure of the project report has been developed, it showcases a lot of the initial sub-sections.
- There are minor spelling mistakes-but it is not a review criteria. 
- Technical terms could be elaborated more i.e. REST API, OPC client-server communication, Docker, GitHub Actions and Watchtower.

_______
- [ ] Re-read report and deem if a sub-section is superficial.
- [ ] Consider adding a problem statement
- [x] Consider expanding the Risks section and dividing it into sub-sections (business, technology).
- [ ] Too many sub-sections in the intial part of the tentative outline?
- [x] Consider elaborating the technical terms more in the section were they are mentioned.

**Comment by kkmp-dk** [comment]
[Extra_Written_review_document_for_group_06.pdf](https://github.com/bierproductie/management/files/5353086/Extra_Written_review_document_for_group_06.pdf)

**Comment by nymann** [comment]
The only part I potentially think we should change here is adding a problem statement, but where do we want to add this? @Kechr

**Comment by Kechr** [comment]
After the section with requirements I think. Where did group 05 place theirs?
